name: "pull_request"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Run website tests
        run: npm run test --if-present
      
      - name: Build website
        run: npm run build
